### ISSUE TITLE
PCA: biplot

### ISSUE THREAD

**Issue by essicolo** [reiinakano/scikit-plot#21]
The `plot_pca_2d_projection` method plots scores and colors by target. Biplots usually plot the scores and vectors with different scalings (scaling 1: distance, and scaling 2: correlation): biplots could included in `plot_pca_2d_projection` or as separate method. The target argument would preferably be optional. The `ecopy` library includes [a nice `biplot` interface](https://github.com/Auerilas/ecopy/blob/master/ecopy/ordination/pca.py).

**Comment by reiinakano** [comment]
After months, this issue can finally be closed thanks to @ryanliwag and #75
