### ISSUE TITLE
Problems with installing on Anaconda (OS X)

### ISSUE THREAD

**Issue by stared** [reiinakano/scikit-plot#24]
After 

```
sudo pip install scikit-plot
```

I get 

> RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

All other libraries I know and use does not require this setup.

**Comment by reiinakano** [comment]
Hi, I am not sure how to solve this as I have not tested it on OS X with Anaconda. 

However, a quick search of your error message seems like it is a problem with Matplotlib on OS X. 

Here's a Stackoverflow post with a solution:
http://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

Let me know if this helps.

**Comment by stared** [comment]
@reiinakano Thanks, it helps!

(Though, I am nor sure why I experience it in the first place; I use `matplotlib` a lot, and libraries based on that (such as `seaborn`), with no similar installation problems.)
