### ISSUE TITLE
Custom Scorer for CV inside plot_learning_curve

### ISSUE THREAD

**Issue by david1309** [reiinakano/scikit-plot#26]
Hello,

I am using cross-validation with a particular metric, Kappa score, rather than the standard accuracy metric.

`cross_val_score(clf, x_train, y_train, scoring=kappa_scorer, cv=kf, n_jobs=-1)`

I would like to to set the CV done inside the `plot_learning_curve` method for each set of `train_sizes` to use the Kappa Scorer and not the accuracy score. I would also like to use the Kappa Scorer to evaluate the models performance for the training set. Is there any way to set this in the `plot_learning_curve` method ?

**Comment by reiinakano** [comment]
Hi @david1309 ! You're right, I can just expose that as an additional parameter. I'll be working on it but feel free to submit a PR if you want.

**Comment by reiinakano** [comment]
Closed by #55
