### ISSUE TITLE
Confusion Matrix plots are confusing with long categories

### ISSUE THREAD

**Issue by ExcaliburZero** [reiinakano/scikit-plot#37]
When you create a confusion matrix plot for a classification problem that has a lot of categories with long names, the names for the "Predicted label" axis can overlap, causing the axis to become unreadable. Even using large dimensions for the `figsize` parameter isn't enough in some cases.

Here is an example.

![scikit_plot_01](https://user-images.githubusercontent.com/4276196/27996318-96ff65e0-64ad-11e7-8885-50f9fb79683c.png)

Perhaps there could be a new optional parameter added to allow the labels on the "Predicted label" axis to be rotated 90 degrees in order to make them easier to read.

**Comment by ExcaliburZero** [comment]
This issue can also occur in other similar cases, such as creating variable importance plots with lots of variables that have long names.

![scikit_plot_02](https://user-images.githubusercontent.com/4276196/27996511-677c2bce-64b1-11e7-9792-97f0778da0f3.png)

**Comment by reiinakano** [comment]
Thanks for pointing this out! I've fixed it in `0.2.7` just released now! 

You can now do `plot_confusion_matrix(..., x_tick_rotation=90)`

**Comment by ExcaliburZero** [comment]
Thanks! It works great now.

![scikit_plot_03](https://user-images.githubusercontent.com/4276196/27996798-35a8eb3a-64b8-11e7-9cea-fb8e35db1e93.png)
