### ISSUE TITLE
conda-forge build!

### ISSUE THREAD

**Issue by ericmjl** [reiinakano/scikit-plot#40]
scikit-plot's so amazing, I decided to make a conda-forge recipe for it! It should up available via conda-forge within a few hours.

**Comment by reiinakano** [comment]
Hi @ericmjl. That sounds awesome! I have to admit, I'm not that familiar with conda so I'm not sure about the implications. Does this mean people will be able to do `conda install scikit-plot`?

**Comment by ericmjl** [comment]
@reiinakano that's right - with a small modification: `conda install -c conda-forge scikit-plot`!

**Comment by reiinakano** [comment]
That's so awesome! Thanks for supporting scikit-plot!
