### ISSUE TITLE
n_jobs plot_learning_curve

### ISSUE THREAD

**Issue by big-doug** [reiinakano/scikit-plot#43]
I'm concerned about the how long it takes given that the model must be trained within the wrapper for the Factory API. The plot_learning_curve method has an n_jobs parameter, but plot_precision_recall_curve doesn't seem to -- am I missing something?

**Comment by reiinakano** [comment]
Your use case seems to be suited for the Functions API. To be honest, the Factory API is something I've been meaning to deprecate for a while, although some people seem to like it so I'll probably just do some overhauling of the functions there.

Anyway, if you want the most efficient way to plot precision-recall curves, use the `plot_precision_recall_curve` function from the Functions API. It only needs the probas + correct labels to plot. Tbh, the `plot_precision_recall_curve` function in the Factory API should probably be called `plot_precision_recall_curve_with_training` or something like that. In retrospect, it was a design mistake to include the cross-validation part into the function itself.
