### ISSUE TITLE
why the auc calculated from plot_roc_curve is different than I manually？

### ISSUE THREAD

**Issue by cloga** [reiinakano/scikit-plot#47]
# calculated use plot_roc_curve
pred = clf.predict_proba(data_test)
skplt.plot_roc_curve(target_test, pred)
plt.show()

it's result is 0.81

# calculated manually
pred_y = clf.predict(data_test)
false_positive_rate, true_positive_rate, thresholds = roc_curve(target_test, pred_y)
roc_auc = auc(false_positive_rate, true_positive_rate)

plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate, true_positive_rate, 'b', label='AUC = %0.2f'% roc_auc)
plt.legend(loc='lower right')
plt.plot([0,1],[0,1],'r--')
plt.xlim([0,1.0])
plt.ylim([0,1.0])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

it's result is 0.72

The problem I encountered is bi-class classification not multi-class classification.

Thank you for your help!

**Comment by reiinakano** [comment]
Hi @cloga, I don't believe it is correct to use the output of `clf.predict` as the input to `roc_curve`. From the sklearn documentation, `y_score` in `roc_curve` must be:

> y_score : array, shape = [n_samples]
> Target scores, can either be probability estimates of the positive class, confidence values, or non-thresholded measure of decisions (as returned by “decision_function” on some classifiers).

Therefore, you need to input the probabilities (or scores from `decision_function`) to get the correct values.

**Comment by cloga** [comment]
Hi @reiinakano, thank you for your revision, I make a mistake about this, thanks very much.
