### ISSUE TITLE
Add new features of plotting Gain Charts and Lift Charts?

### ISSUE THREAD

**Issue by hangyao** [reiinakano/scikit-plot#63]
Hi Team!

I would like to know if you have any plan of adding new functions to plot Gain Charts and Lift Charts since they are popular in data science projects. 

https://www.ibm.com/support/knowledgecenter/en/SSLVMB_23.0.0/spss/tutorials/mlp_bankloan_outputtype_02.html

https://docs.microsoft.com/en-us/sql/analysis-services/data-mining/lift-chart-analysis-services-data-mining

Thank you!

**Comment by reiinakano** [comment]
These look very useful. I have been thinking about what plots I should be adding next actually.

I will implement these next. Thank you!
