### ISSUE TITLE
AttributeError: module 'scikitplot' has no attribute 'metrics'

### ISSUE THREAD

**Issue by cloga** [reiinakano/scikit-plot#68]
when I use updated version I got this error. And it seems some sample code need update.

**Comment by reiinakano** [comment]
If you have the updated version, then you shouldn't get this error. Can you run

`print(scikitplot.__version__)`

You are probably still on an older version.

Only the notebooks are currently outdated. All the other sample code is up to date with v0.3.1.

**Comment by cloga** [comment]
thanks you are right.
