### ISSUE TITLE
Plot ONLY one class

### ISSUE THREAD

**Issue by foo123** [reiinakano/scikit-plot#83]
Hello i have a precision-recall curve where i plot as the following:

```python
skplt.metrics.plot_precision_recall_curve(y_test, y_probas, curves=['each_class'])
```

I have two classes in the data (one positive and one negative class with labels 1 and -1 respectively). Questions: How can I plot ONLY the positive class?

Thank you

**Comment by reiinakano** [comment]
No way to do this currently. This could be a PR though.

**Comment by foo123** [comment]
Maybe if the curves parameter is a number (or a string different than each_class and micro), plot only this class from the data. This is what i can think right now

**Comment by lugq1990** [comment]
@foo123  I have added a new key word as "positive" for the case when just want to plot the positive class. Default is the first class represented as the "positive". I will submit to it. @reiinakano please check it whether it is OK.

**Comment by foo123** [comment]
@lugq1990 Please make sure the positive class is indeed the positive class. For example check the label is a positive number (this is how i make positive classes).
Thank you

**Comment by lugq1990** [comment]
@foo123 OK，because the owner want to rebuild the project, maybe I will need a little time to make the need of you satisfied.  If I have finished it, I will tell you right now.

**Comment by foo123** [comment]
@reiinakano thanks i take note.

**Comment by siddagra** [comment]
This is absolutely stupid. I spent HOURS trying to get this to work only to realise this library does not even support the most basic machine learning functionality: binary classification. U guys should seriously fix this, no wonder no one uses this library. Will move to sklearn and likely never use this again.
