### ISSUE TITLE
multilabel-indicator format is not supported

### ISSUE THREAD

**Issue by SP2014** [reiinakano/scikit-plot#85]
While plotting the roc curve I'm getting this error. please help

**Comment by lugq1990** [comment]
Hi, @SP2014 For now, the plot_roc_curve do not support for the multilabel-indicator. But I am wondered that if you want to plot the multilabel classes, what you need is that want to plot the each label's ROC curve? For example, you have each data to have most 2 labels as 0 and 1, you fit your model and get your probabilities of each test data for different label, you want to plot the label 0 and label 1 ROC curve. Is that true?
