### ISSUE TITLE
ModuleNotFoundError: No module named 'scikitplot'

### ISSUE THREAD

**Issue by martadmnoronha** [reiinakano/scikit-plot#88]
Hi. I'm beginner in python and I got this error when I tried to run a code that uses scikitplot in w7. I'm using Spyder to do it. I used this command "import scikitplot  as skplt".
I checked if scikitplot is installed and it is installed in my computer. I ran this code in Ubuntu last year, but I need to run again in w7 and it is not working in this SO.  How can I solve this issue, please?

**Comment by martadmnoronha** [comment]
Hi again. I discovered the problem. The Python's path in Spyder was set to the directory on Anaconda. I installed the conda and later installed the package using the command "conda install -c conda-forge scikit-plot". It's working now. 
Anyway, thank you for making the scikitplot available.It's a valuable tool.

**Comment by utkarshshri1016** [comment]
can you share the command for those who don't use Anaconda
