### ISSUE TITLE
Error installing No module named sklearn.metrics

### ISSUE THREAD

**Issue by ArthurZ** [reiinakano/scikit-plot#9]
Hi there,
I am getting an error installing it
``` bash
pip install scikit-plot                                                              ~ 1
Collecting scikit-plot
  Downloading scikit-plot-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\arthur\.babun\cygwin\tmp\pip-build-yrgynz\scikit-plot\setup.py", line 9, in <module>
        import scikitplot
      File "c:\users\arthur\.babun\cygwin\tmp\pip-build-yrgynz\scikit-plot\scikitplot\__init__.py", line 5, in <module>
        from scikitplot.classifiers import classifier_factory
      File "c:\users\arthur\.babun\cygwin\tmp\pip-build-yrgynz\scikit-plot\scikitplot\classifiers.py", line 7, in <module>
        from scikitplot import plotters
      File "c:\users\arthur\.babun\cygwin\tmp\pip-build-yrgynz\scikit-plot\scikitplot\plotters.py", line 9, in <module>
        from sklearn.metrics import confusion_matrix
    ImportError: No module named sklearn.metrics

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\arthur\.babun\cygwin\tmp\pip-build-yrgynz\scikit-plot\
```

**Comment by reiinakano** [comment]
Hey, thanks for trying out scikit-plot. 

It looks like you might not have scikit-learn installed. Please install scikit-learn first. :)

**Comment by ArthurZ** [comment]
Thanks,
oh yeah, but then it required skipy that could not get installed.

**Comment by reiinakano** [comment]
Hmm, I believe scipy is a dependency of scikit-learn so you can't really use scikit-learn without installing scipy as well.

**Comment by ArthurZ** [comment]
I verified this as a yes.
I am hitting the 
``` bash
numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
``` 
error.
Unfortunately, it was made on Windows a long and convoluted process to get it up and running: [http://stackoverflow.com/questions/28190534/windows-scipy-install-no-lapack-blas-resources-found](http://stackoverflow.com/questions/28190534/windows-scipy-install-no-lapack-blas-resources-found)

**Comment by reiinakano** [comment]
Oh okay. I suppose this is an issue with Windows and Scipy then. Hope you get it up and running and thanks for trying out scikit-plot!
